services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app  # monta a raiz do projeto no container
    env_file:
      - .env
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --reload"
    depends_on:
      - postgresql
      - postgresql-test

  celery_worker:
    build: .
    command: celery -A app.services.celery.celery_app worker --loglevel=info
    depends_on:
      - broker
      - postgresql
    env_file:
      - .env
  celery_beat:
    build: .
    command: celery -A app.services.celery.celery_app beat --loglevel=info
    depends_on:
      - broker
      - postgresql
    env_file:
      - .env


  broker:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=biblioteca
    volumes:
      - biblioteca_db_data:/var/lib/postgresql/data

  postgresql-test:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgresql-test/biblioteca_test?user=dev_gabriel&password=university
      - POSTGRES_DB=biblioteca_test
    volumes:
      - biblioteca_test_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - postgresql

volumes:
  biblioteca_db_data:
  biblioteca_test_db_data:
