"""url de imagens

Revision ID: 150834edeb0e
Revises: 2a3c4c649b97
Create Date: 2025-02-15 16:33:39.198096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150834edeb0e'
down_revision: Union[str, None] = '2a3c4c649b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livro', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('profile_picture_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'profile_picture_url')
    op.drop_column('livro', 'image_url')
    # ### end Alembic commands ###
